# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DnZkxvupKS4pN03zAMCfxnJ9dJPUbZ7k
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib

# 1. Page Configuration
st.set_page_config(page_title="Migration Costs Index", page_icon="🌎", layout="centered")

# 2. Load Artifacts
@st.cache_resource
def load_artifacts():
    return joblib.load('migration_index_model.pkl')

artifacts = load_artifacts()
models = artifacts['models']
scalers = artifacts['scalers']
features = artifacts['features']

# Helper Function to align user input with training columns
def align_and_scale(input_dict, reference_cols, scaler):
    df = pd.DataFrame([input_dict])
    df_encoded = pd.get_dummies(df)

    # Fill missing columns with 0
    for col in reference_cols:
        if col not in df_encoded.columns:
            df_encoded[col] = 0

    # Ensure exact column order
    df_aligned = df_encoded[reference_cols]

    # Scale
    return pd.DataFrame(scaler.transform(df_aligned), columns=reference_cols)

# 3. Web App UI
st.title("🌎 The Hidden Costs of Migration Index")
st.markdown("### *Calculate your Financial Survival Index before moving to a new US State.*")
st.divider()

st.sidebar.header("🛠️ Your Profile Settings")

# Professional Details
st.sidebar.subheader("💼 Professional Details")
age = st.sidebar.slider("Age", 18, 70, 30)
gender = st.sidebar.selectbox("Gender", ["Male", "Female"])
education = st.sidebar.selectbox("Education Level", ["High School", "Bachelor's", "Master's", "PhD"])
# (Expand this list based on your actual dataset)
job_title = st.sidebar.selectbox("Job Title", [
    "Software Engineer", "Data Analyst", "Senior Manager", "Sales Associate",
    "Director", "Marketing Analyst", "Product Manager", "HR Manager", "Financial Analyst",
    "Senior Data Scientist", "Director of Engineering"
])
experience = st.sidebar.slider("Years of Experience", 0, 40, 5)

# Housing Details
st.sidebar.subheader("🏠 Housing & Location")
# Common states (You can add the rest of the 50 states here)
state = st.sidebar.selectbox("Target State (Code)", ["NY", "CA", "TX", "FL", "IL", "PA", "OH", "GA", "NC", "MI", "WA"])
sqft = st.sidebar.slider("Apartment Size (Sq Ft)", 400, 4000, 1000)

# Health Details
st.sidebar.subheader("⚕️ Health Profile")
bmi = st.sidebar.slider("BMI", 15.0, 50.0, 25.0)
smoker = st.sidebar.selectbox("Do you smoke?", ["no", "yes"])

# 4. Calculation Button
if st.button("🚀 Calculate Viability", use_container_width=True):
    with st.spinner("Crunching the numbers with AI..."):

        # --- Income Prediction ---
        inc_input = {'Age': age, 'Gender': gender, 'Education Level': education, 'Job Title': job_title, 'Years of Experience': experience}
        inc_scaled = align_and_scale(inc_input, features['salary'], scalers['salary'])
        pred_income_monthly = models['salary'].predict(inc_scaled)[0] / 12.0

        # --- Rent Prediction ---
        rent_input = {'square_feet': sqft, 'bathrooms': 1, 'bedrooms': 1, 'state': state, 'pets_allowed': 'No'}
        rent_scaled = align_and_scale(rent_input, features['rent'], scalers['rent'])
        pred_rent_monthly = np.expm1(models['rent'].predict(rent_scaled)[0]) # Reversing Log

        # --- Insurance Prediction ---
        ins_input = {'age': age, 'bmi': bmi, 'children': 0, 'sex': 1 if gender == 'Male' else 0,
                     'smoker': 1 if smoker == 'yes' else 0, 'region_northwest': 0, 'region_southeast': 0, 'region_southwest': 1}
        ins_scaled = align_and_scale(ins_input, features['insurance'], scalers['insurance'])
        pred_ins_monthly = np.expm1(models['insurance'].predict(ins_scaled)[0]) / 12.0 # Reversing Log

        # --- Utilities Prediction ---
        util_input = {'square_feet': sqft, 'family_size': 1, 'ac_heating_usage_hrs': 6, 'state': state}
        util_scaled = align_and_scale(util_input, features['utilities'], scalers['utilities'])
        pred_util_monthly = models['utilities'].predict(util_scaled)[0]

        # --- Final Math ---
        total_costs = pred_rent_monthly + pred_ins_monthly + pred_util_monthly
        financial_index = pred_income_monthly - total_costs

        # 5. Display Results
        st.subheader("📊 Financial Survival Report")

        col1, col2 = st.columns(2)
        with col1:
            st.info(f"**Predicted Monthly Salary:**\n\n${pred_income_monthly:,.2f}")
        with col2:
            st.error(f"**Total Estimated Costs:**\n\n${total_costs:,.2f}")

        st.write(f"- Rent: ${pred_rent_monthly:,.2f}")
        st.write(f"- Med Insurance: ${pred_ins_monthly:,.2f}")
        st.write(f"- Utilities: ${pred_util_monthly:,.2f}")

        st.divider()
        st.metric(label="💰 SURVIVAL INDEX (Net Cash Flow)", value=f"${financial_index:,.2f}")

        if financial_index > 500:
            st.success("🟢 **VERDICT: SAFE.** You have a comfortable buffer. Migrating here is financially sound.")
            st.balloons()
        elif financial_index > 0:
            st.warning("🟡 **VERDICT: TIGHT.** It is viable, but margins are tight. Budget carefully.")
        else:
            st.error("🔴 **VERDICT: DANGER.** The predicted costs exceed your likely income. Do not migrate without a secured higher-paying job.")